### ISSUE TITLE
Feature Comparison with Asan, Msan, and lsan

### ISSUE THREAD

**Issue by LifeIsStrange** [nokia/memory-profiler#4]
What are the benefits of your tool over them?

For example big limitation of Asan + Msan is that they can't be used simultaneously. 
So I can't check invalid  use of uninitialised memory and invalid use of adresses.
Can this tool check both at the same time?

What about performance?
Or am I misunderstanding and this is only a profiler not a memory debugger?
If so how does it compare to DHAT and others?

**Comment by koute** [comment]
This is an entirely different type of tool than ASan/MSan/etc. It's only a memory profiler, so it doesn't check whenever you access uninitialized memory, or invalid pointers, or that you don't trigger undefined behavior, etc.

It should be several orders of magnitude faster than any tool running on Valgrind purely due to the fact that it's running fully natively, unlike Valgrind which is essentially a full blown CPU emulator.

Basically, what this profiler does is that it only replaces `malloc`/`realloc`/`free`/etc. leaving everything else intact. Inside of one of those replaced functions it grabs a stack trace, calls the original function, and sends that stack trace along with the information about the allocation itself to another thread for processing. It also employs some other tricks so that it should be even faster than other `LD_PRELOAD`-based memory profilers (like [Heaptrack](https://github.com/KDE/heaptrack)).

Did this answer your question?

**Comment by LifeIsStrange** [comment]
Perfect answering, I'll be happy to use this tool :)
